apiVersion: app/v1beta1
kind: ContainerApp
metadata:
  name: ca-nbrly-nbapp1-dev
  resourceGroup: rg-astrapia-dev
spec:
  environmentId: /subscriptions/984059e7-2907-4273-8569-703dddc5adfa/resourceGroups/rg-astrapia-dev/providers/Microsoft.App/managedEnvironments/cae-nbrly-dev
  identity:
    type: UserAssigned
    userAssignedIdentities:
      /subscriptions/984059e7-2907-4273-8569-703dddc5adfa/resourceGroups/rg-astrapia-dev/providers/Microsoft.ManagedIdentity/userAssignedIdentities/nbrly-dev-uami: {}
  configuration:
    registries:
      - server: astradevacr.azurecr.io
        identity: /subscriptions/984059e7-2907-4273-8569-703dddc5adfa/resourceGroups/rg-astrapia-dev/providers/Microsoft.ManagedIdentity/userAssignedIdentities/nbrly-dev-uami
    ingress:
      external: false
      targetPort: 8000
      transport: http
      allowInsecure: false
    secrets: []
  template:
    containers:
      - name: nbapp1
        image: astradevacr.azurecr.io/astradevacr.azurecr.io/nbrly/nbapp1:latest
        env:
          - name: ENVIRONMENT
            value: "dev"
          - name: ROOT_PATH
            value: "/app1"
          - name: APP_NAME
            value: "ca-nbrly-nbapp1-dev"
          - name: TENANT
            value: "nbrly"
          - name: APP_TYPE
            value: "nbapp1"
          - name: AZURE_CLIENT_ID
            value: "#{NBRLY_UAMI_CLIENT_ID}#"
          - name: PORT
            value: "8000"
        resources:
          cpu: 0.5
          memory: 1.0Gi
        probes:
          - type: Liveness
            httpGet:
              path: /health/live
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
          - type: Readiness
            httpGet:
              path: /health/ready
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
    scale:
      minReplicas: 1
      maxReplicas: 3
      rules:
        - name: http-scaling
          http:
            metadata:
              concurrentRequests: "100"
